Repository domainsproject/register, pull requests merged in 2025-07, with the labels that each got.

#38 benxx-project.owns.it.com.json
  domains/benxx-project.owns.it.com.json
Labels: CLA Required, Awaiting Response

#39 Create benxx-project.owns.it.com.jsonson
  domains/benxx-project.json
Labels: CLA Signed, Awaiting Response

#46 Create 0mogus.owns.it.com
  domains/0mogus.owns.it.com.json
Labels: CLA Signed

#47 Please, accept my domain registration request
  domains/_vercel.glyphs.owns.it.com.json
  domains/glyphs.owns.it.com.json
Labels: CLA Required

#53 Create hamza.owns.it.com.json
  domains/hamza.owns.it.com.json
Labels: CLA Required
